name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: windows-latest
      steps:
        - name: Print greeting
          run: echo "Hello World"
        - name: Print goodbye
          run: echo "Done - bye!"
